compressionLevel: mixed

enableGlobalCache: true

nodeLinker: node-modules

npmAuthToken: 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

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
